# Generated by Django 4.0.2 on 2022-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=540)),
                ('image', models.ImageField(upload_to='giveaway_image')),
                ('created', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
